Add files via upload
sophy-korp/CPP-2023-5-1-Calculator pull request #1
Opened 2023-10-01 10:06 UTC by sophy-korp

2023-10-08 15:50 UTC, Kauter1989 requested changes

2023-10-08 15:50 UTC, Kauter1989 commented on CMakeLists.txt
> +add_library(sin SHARED ./plugins/sin.cpp "plugins/sin.cpp" "Dll_Reader.cpp" "Dll_Reader.h")
Этого не должно быть, т.к. число и нужные библиотеки ты определяешь в рантайме, и можно часть выкинуть/добавить новые без перекомпиляции

2023-10-08 15:50 UTC, Kauter1989 commented on Calculator.h
> +	std::map<std::string, std::function<double(double, double)>> functionalities;
функции могут быть и унарными

2023-10-08 15:50 UTC, Kauter1989 commented on Dll_Reader.h
> +#ifndef DLL_READER
почему не pragma once?

2023-10-08 15:50 UTC, Kauter1989 commented on Plugins/sin.cpp
> +double universal_func(double num) {
нет никакой привязки к С++ - это должно было насторожить)

2023-10-09 15:11 UTC, sophy-korp commented on Calculator.h
> +	std::map<std::string, std::function<double(double, double)>> functionalities;
Это map со "стандартными" функциями (+, -, *, /, ^), ни одна из которых не является унарной. Уточните, пожалуйста, что необходимо поправить.

2023-10-11 17:02 UTC, Kauter1989 requested changes

2023-10-11 17:02 UTC, Kauter1989 commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
Что именно из 20 стандарта вы используете?

2023-10-11 17:02 UTC, Kauter1989 commented on Calculator.h
> +	std::map<std::string, std::function<double(double, double)>> functionalities;
Каким образом добавить факториал?

2023-10-11 17:33 UTC, sophy-korp commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
Да, Вы правы, ничего. Заменю на 17 стандарт.

2023-10-25 16:40 UTC, closed without merging